import type { User } from "@/types/user"

export const users: User[] = [
  {
    id: "L000001",
    firstName: "David",
    lastName: "Nguyen",
    email: "david.nguyen@gmail.com",
    phone: "(322) 243-3452",
    type: "Loan Officer",
    experience: "5 years",
    status: "ACTIVE",
    website: "david.com",
    image: "/images/users/user_1.png",
  },
  {
    id: "UW00001",
    firstName: "Jennie",
    lastName: "Pink",
    email: "jenniepink@gmail.com",
    phone: "(322) 243-3452",
    type: "Underwriter",
    experience: "5 years",
    status: "ACTIVE",
    website: "jennie.com",
    image: "/images/users/user_2.png",
  },
  {
    id: "LP00001",
    firstName: "Pep",
    lastName: "Guardiola",
    email: "pepguardiola@gmail.com",
    phone: "(322) 243-3452",
    type: "Loan Processor",
    experience: "5 years",
    status: "ACTIVE",
    website: "pep.com",
    image: "/images/users/user_3.png",
  },
  {
    id: "AD00001",
    firstName: "Bruno",
    lastName: "Mar",
    email: "brunomors@gmail.com",
    phone: "(322) 243-3452",
    type: "Admin",
    experience: "5 years",
    status: "ACTIVE",
    website: "bruno.com",
    image: "/images/users/user_1.png",
  },
  {
    id: "ME00001",
    firstName: "David",
    lastName: "Beckham",
    email: "davidbeckham@gmail.com",
    phone: "(322) 243-3452",
    type: "Member",
    experience: "5 years",
    status: "ACTIVE",
    website: "beckham.com",
    image: "/images/users/user_2.png",
  },
  {
    id: "L000001",
    firstName: "David",
    lastName: "Nguyen",
    email: "david.nguyen@gmail.com",
    phone: "(322) 243-3452",
    type: "Loan Officer",
    experience: "5 years",
    status: "ACTIVE",
    website: "david.com",
    image: "/images/users/user_1.png",
  },
  {
    id: "UW00001",
    firstName: "Jennie",
    lastName: "Pink",
    email: "jenniepink@gmail.com",
    phone: "(322) 243-3452",
    type: "Underwriter",
    experience: "5 years",
    status: "ACTIVE",
    website: "jennie.com",
    image: "/images/users/user_2.png",
  },
  {
    id: "LP00001",
    firstName: "Pep",
    lastName: "Guardiola",
    email: "pepguardiola@gmail.com",
    phone: "(322) 243-3452",
    type: "Loan Processor",
    experience: "5 years",
    status: "ACTIVE",
    website: "pep.com",
    image: "/images/users/user_3.png",
  },
  {
    id: "AD00001",
    firstName: "Bruno",
    lastName: "Mar",
    email: "brunomors@gmail.com",
    phone: "(322) 243-3452",
    type: "Admin",
    experience: "5 years",
    status: "ACTIVE",
    website: "bruno.com",
    image: "/images/users/user_1.png",
  },
  {
    id: "ME00001",
    firstName: "David",
    lastName: "Beckhamm",
    email: "davidbeckham@gmail.com",
    phone: "(322) 243-3452",
    type: "Member",
    experience: "5 years",
    status: "ACTIVE",
    website: "beckham.com",
    image: "/images/users/user_2.png",
  },
]

export const todoItems = [
  { id: 1, label: "Review Loan Applications", link: "#" },
  { id: 2, label: "Contact to Borrower", link: "#" },
]

export const loanDocuments = [
  {
    index: "01",
    borrowerName: "Ms. Hang Nguyen",
    loanId: "#LA00001",
    lender: "AD Mortgage",
    interestRate: "6% (6.168% APR)",
    progress: 68,
    status: "IN PROGRESS",
  },
  {
    index: "02",
    borrowerName: "Ms. Hang Nguyen",
    loanId: "#LA00001",
    lender: "AD Mortgage",
    interestRate: "6% (6.168% APR)",
    progress: 68,
    status: "IN PROGRESS",
  },
]

export const generalInformation = [
  {
    label: "First Name",
    value: "David",
  },
  {
    label: "Last Name",
    value: "Nguyen",
  },
  {
    label: "Experience",
    value: "5 years",
  },
  {
    label: "Personal Website",
    value: "david.com",
    isLink: true,
  },
]
